### ISSUE TITLE
Page "locked" by Nextcloud

### ISSUE THREAD

**Issue by mitchelldehaven** [egorsmkv/speech-recognition-uk#21]
The ~ 1,200 hour dataset listed for download at Nextcloud (https://nx16725.your-storageshare.de/s/cAbcBeXtdz7znDN) is "locked". Is the only way to access this dataset now via torrent (https://academictorrents.com/details/fcf8bb60c59e9eb583df003d54ed61776650beb8)?

**Comment by egorsmkv** [comment]
hello, thanks for the notice

will work on it

**Comment by egorsmkv** [comment]
it works now
