### ISSUE TITLE
STT Example?

### ISSUE THREAD

**Issue by hellcezar** [egorsmkv/speech-recognition-uk#36]
Greetings, how i can use model to recognize speech to text, like from wav/mp3/mp4 file and record all speech to file? probably it can to make time stumps like in srt files

**Comment by egorsmkv** [comment]
https://github.com/egorsmkv/speech-recognition-uk/tree/master/speech-to-text

here are the python scripts you can use

**Comment by egorsmkv** [comment]
>  to make time stumps like in srt files

for this you can use VAD like PyAnnote or Whisper model
