### ISSUE TITLE
Train models with specific words 

### ISSUE THREAD

**Issue by Alexbeard** [egorsmkv/speech-recognition-uk#7]
Guys, thank you for your instruction in Russian on how to create a model. That is very helpful.
I want to leave an issue as a question. Can we create a model for specific words, for example, the words: Yes or No.
If yes how much the result size of model approximately will be.

**Comment by egorsmkv** [comment]
If to say about VOSK then the model size will be small for your case.

**Comment by egorsmkv** [comment]
I'm closing the issue due to inactivity.
